# Generated by Django 3.2.9 on 2021-11-30 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsupervisor',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club', to='club.club'),
        ),
        migrations.AddField(
            model_name='clubsupervisor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clubsupervisor_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubcoordinator',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_club', to='club.club'),
        ),
        migrations.AddField(
            model_name='clubcoordinator',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clubcoordinator_user', to='accounts.student'),
        ),
    ]
