# Generated by Django 4.0 on 2021-12-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hes_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
