# Generated by Django 4.0 on 2021-12-23 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubfollowing',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='club.club'),
        ),
        migrations.AlterField(
            model_name='clubfollowing',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followees', to='accounts.student'),
        ),
    ]
