# Generated by Django 4.0 on 2021-12-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='rate',
        ),
    ]
