# Generated by Django 4.0 on 2021-12-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_clubfollowing_club_alter_clubfollowing_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='logo',
        ),
    ]
