# Generated by Django 4.0 on 2021-12-25 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'A'), ('MA', 'Ma'), ('B', 'B'), ('EA', 'Ea'), ('EB', 'Eb'), ('EE', 'Ee'), ('ODEON', 'Odeon'), ('F', 'F'), ('FB', 'Fb'), ('FF', 'Ff'), ('G', 'G'), ('C', 'C'), ('M', 'M'), ('U', 'U'), ('V', 'V'), ('SU', 'Su'), ('S', 'S'), ('SA', 'Sa'), ('SB', 'Sb')], max_length=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[], max_length=3)),
                ('is_available', models.BooleanField(default=True)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='place.building')),
            ],
        ),
    ]
