# Generated by Django 4.0 on 2021-12-25 10:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.TextField(choices=[('business', 'Business'), ('entertainment', 'Entertainment'), ('sport', 'Sport'), ('policy', 'Policy')])),
                ('event_status', models.TextField(choices=[('pending', 'Pending'), ('past', 'Past'), ('upcoming', 'Upcoming'), ('rejected', 'Rejected')])),
                ('description', models.TextField()),
                ('ge_status', models.BooleanField(default=False)),
                ('ge_point', models.IntegerField(default='10')),
                ('is_online', models.BooleanField(default=False)),
                ('zoom_link', models.URLField(blank=True)),
                ('location', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_events', to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='EventEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_events', to='event.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='accounts.student')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
