# Generated by Django 4.0 on 2021-12-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.TextField(choices=[('pending', 'Pending'), ('past', 'Past'), ('upcoming', 'Upcoming'), ('rejected', 'Rejected')], default='pending'),
        ),
    ]
