# Generated by Django 4.0 on 2021-12-23 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='datetime',
        ),
    ]
