# Generated by Django 4.0 on 2021-12-24 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('event', '0002_rename_date_event_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventenrollment',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_events', to='event.event'),
        ),
        migrations.AlterField(
            model_name='eventenrollment',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='accounts.student'),
        ),
    ]
