# Generated by Django 4.0 on 2021-12-25 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('event', '0003_alter_event_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventenrollment',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='eventenrollment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='event.event'),
        ),
        migrations.AlterField(
            model_name='eventenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_events', to='accounts.student'),
        ),
    ]
